package io.github.berrachdi.springbootjobmonitor.exchange.engine;

import io.github.berrachdi.springbootjobmonitor.exchange.domain.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.PriorityQueue;
import java.util.concurrent.locks.ReentrantLock;

/**
 * Thread-safe order book for a single {@link CurrencyPair}.
 *
 * <p>Each instance holds its own {@link ReentrantLock}, so matching on different
 * currency pairs can proceed in parallel without blocking each other.
 *
 * <ul>
 *   <li>Buy orders are stored in a max-heap (highest price first).
 *   <li>Sell orders are stored in a min-heap (lowest price first).
 * </ul>
 */
public class OrderBook {

    private final CurrencyPair pair;

    /** One lock per order-book instance — never a global lock. */
    private final ReentrantLock lock = new ReentrantLock();

    /** Max-heap: highest buy price at the head. */
    private final PriorityQueue<Order> buyOrders =
            new PriorityQueue<>(Comparator.comparing(Order::getPrice).reversed());

    /** Min-heap: lowest sell price at the head. */
    private final PriorityQueue<Order> sellOrders =
            new PriorityQueue<>(Comparator.comparing(Order::getPrice));

    public OrderBook(CurrencyPair pair) {
        this.pair = pair;
    }

    /**
     * Submits an order, matches it against the opposite side, and returns all
     * trades that were generated.  Any unfilled remainder is placed on the book.
     *
     * @param order the incoming order (must not be {@code null})
     * @return list of trades generated by this submission (may be empty)
     */
    public List<Trade> submitOrder(Order order) {
        lock.lock();
        try {
            return match(order);
        } finally {
            lock.unlock();
        }
    }

    private List<Trade> match(Order order) {
        List<Trade> trades = new ArrayList<>();
        PriorityQueue<Order> oppositeBook = order.getSide() == Side.BUY ? sellOrders : buyOrders;

        while (!oppositeBook.isEmpty() && order.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
            Order best = oppositeBook.peek();

            boolean priceMatches = order.getSide() == Side.BUY
                    ? order.getPrice().compareTo(best.getPrice()) >= 0   // buyer willing to pay >= ask
                    : order.getPrice().compareTo(best.getPrice()) <= 0;  // seller willing to accept <= bid

            if (!priceMatches) {
                break;
            }

            oppositeBook.poll();

            BigDecimal tradeQty = order.getRemainingQuantity()
                    .min(best.getRemainingQuantity());

            order.fill(tradeQty);
            best.fill(tradeQty);

            Order buyOrder  = order.getSide() == Side.BUY ? order : best;
            Order sellOrder = order.getSide() == Side.SELL ? order : best;

            trades.add(Trade.builder()
                    .pair(pair)
                    .price(best.getPrice())   // trade executes at the resting order's price
                    .quantity(tradeQty)
                    .buyOrderId(buyOrder.getId())
                    .sellOrderId(sellOrder.getId())
                    .build());

            if (best.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
                oppositeBook.add(best);   // put partially filled resting order back
            }
        }

        // If the incoming order still has remaining quantity, add it to the book
        if (order.getRemainingQuantity().compareTo(BigDecimal.ZERO) > 0) {
            if (order.getSide() == Side.BUY) {
                buyOrders.add(order);
            } else {
                sellOrders.add(order);
            }
        }

        return trades;
    }

    /** Returns the number of open buy orders currently on the book. */
    public int getBuyOrderCount() {
        lock.lock();
        try {
            return buyOrders.size();
        } finally {
            lock.unlock();
        }
    }

    /** Returns the number of open sell orders currently on the book. */
    public int getSellOrderCount() {
        lock.lock();
        try {
            return sellOrders.size();
        } finally {
            lock.unlock();
        }
    }

    public CurrencyPair getPair() {
        return pair;
    }
}
