name: Maven tests

on:
  pull_request:    # run on any pull requests 
    branches:
      - main
  push:            # also runs if some pushed directly to the 'main' branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn test
